package com.example.administrator.mydemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.mydemo.model.FileDownLoadBean;

import com.example.administrator.mydemo.db.FileDownLoadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileDownLoadBeanDaoConfig;

    private final FileDownLoadBeanDao fileDownLoadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileDownLoadBeanDaoConfig = daoConfigMap.get(FileDownLoadBeanDao.class).clone();
        fileDownLoadBeanDaoConfig.initIdentityScope(type);

        fileDownLoadBeanDao = new FileDownLoadBeanDao(fileDownLoadBeanDaoConfig, this);

        registerDao(FileDownLoadBean.class, fileDownLoadBeanDao);
    }
    
    public void clear() {
        fileDownLoadBeanDaoConfig.clearIdentityScope();
    }

    public FileDownLoadBeanDao getFileDownLoadBeanDao() {
        return fileDownLoadBeanDao;
    }

}
