package com.example.administrator.mydemo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.mydemo.model.FileDownLoadBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_DOWN_LOAD_BEAN".
*/
public class FileDownLoadBeanDao extends AbstractDao<FileDownLoadBean, Long> {

    public static final String TABLENAME = "FILE_DOWN_LOAD_BEAN";

    /**
     * Properties of entity FileDownLoadBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property FileName = new Property(2, String.class, "fileName", false, "FILE_NAME");
        public final static Property FilePath = new Property(3, String.class, "filePath", false, "FILE_PATH");
        public final static Property Length = new Property(4, long.class, "length", false, "LENGTH");
        public final static Property Seek = new Property(5, long.class, "seek", false, "SEEK");
        public final static Property Finished = new Property(6, int.class, "finished", false, "FINISHED");
        public final static Property Filemtime = new Property(7, String.class, "filemtime", false, "FILEMTIME");
        public final static Property FilePostfix = new Property(8, String.class, "filePostfix", false, "FILE_POSTFIX");
    }


    public FileDownLoadBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FileDownLoadBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_DOWN_LOAD_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"URL\" TEXT," + // 1: url
                "\"FILE_NAME\" TEXT," + // 2: fileName
                "\"FILE_PATH\" TEXT," + // 3: filePath
                "\"LENGTH\" INTEGER NOT NULL ," + // 4: length
                "\"SEEK\" INTEGER NOT NULL ," + // 5: seek
                "\"FINISHED\" INTEGER NOT NULL ," + // 6: finished
                "\"FILEMTIME\" TEXT," + // 7: filemtime
                "\"FILE_POSTFIX\" TEXT);"); // 8: filePostfix
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_DOWN_LOAD_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FileDownLoadBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
        stmt.bindLong(5, entity.getLength());
        stmt.bindLong(6, entity.getSeek());
        stmt.bindLong(7, entity.getFinished());
 
        String filemtime = entity.getFilemtime();
        if (filemtime != null) {
            stmt.bindString(8, filemtime);
        }
 
        String filePostfix = entity.getFilePostfix();
        if (filePostfix != null) {
            stmt.bindString(9, filePostfix);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FileDownLoadBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
 
        String filePath = entity.getFilePath();
        if (filePath != null) {
            stmt.bindString(4, filePath);
        }
        stmt.bindLong(5, entity.getLength());
        stmt.bindLong(6, entity.getSeek());
        stmt.bindLong(7, entity.getFinished());
 
        String filemtime = entity.getFilemtime();
        if (filemtime != null) {
            stmt.bindString(8, filemtime);
        }
 
        String filePostfix = entity.getFilePostfix();
        if (filePostfix != null) {
            stmt.bindString(9, filePostfix);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public FileDownLoadBean readEntity(Cursor cursor, int offset) {
        FileDownLoadBean entity = new FileDownLoadBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fileName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // filePath
            cursor.getLong(offset + 4), // length
            cursor.getLong(offset + 5), // seek
            cursor.getInt(offset + 6), // finished
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // filemtime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // filePostfix
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FileDownLoadBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFileName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFilePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLength(cursor.getLong(offset + 4));
        entity.setSeek(cursor.getLong(offset + 5));
        entity.setFinished(cursor.getInt(offset + 6));
        entity.setFilemtime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFilePostfix(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FileDownLoadBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FileDownLoadBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FileDownLoadBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
